services:
  kong:
    image: kong/kong-gateway:latest
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/kong/kong.yml"
      KONG_LOG_LEVEL: debug
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"  # Public API Gateway Port
      - "8001:8001"  # Admin API Port
    networks:
      - live_comments_network  # Attach Kong to the existing network

networks:
  live_comments_network:
    external: true # Ensure Kong joins the existing network
