services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - live_comments_network

networks:
  live_comments_network:
    name: live_comments_network
    driver: bridge
